;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        iy-go-to-char--command
        iy-go-to-char-quit
        org-beginning-of-line
        org-end-of-line
        paredit-forward-kill-word
        ruby-end-space
        ))

(setq mc/cmds-to-run-once
      '(
        rectangle-number-lines
        ))
