;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        c-electric-delete-forward
        c-electric-semi&comma
        delete-horizontal-space
        forward-symbol
        indent-region
        iy-go-to-char--command
        iy-go-to-char-kill-region
        iy-go-to-char-kill-ring-save
        iy-go-to-char-quit
        kill-region
        org-beginning-of-line
        org-end-of-line
        paredit-backward-kill-word
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-meta-doublequote
        paredit-open-round
        paredit-splice-sexp
        ruby-end-space
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        whole-line-or-region-yank
        yas-expand
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        rectangle-number-lines
        ))
